# Generated by Django 6.0.6 on 2026-06-13 19:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='sets, rolls, sushi, hot, desserts, drinks, sauces', max_length=32, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, help_text='Например: «ЛУЧШИЙ ВЫБОР ДЛЯ КОМПАНИИ»', max_length=200, verbose_name='Подзаголовок секции')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория меню',
                'verbose_name_plural': 'Категории меню',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Новый'), ('confirmed', 'Подтверждён'), ('preparing', 'Готовится'), ('delivering', 'В доставке'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('subtotal', models.PositiveIntegerField(default=0, verbose_name='Сумма без скидки, ₽')),
                ('discount_amount', models.PositiveIntegerField(default=0, verbose_name='Скидка, ₽')),
                ('delivery_fee', models.PositiveIntegerField(default=0, verbose_name='Доставка, ₽')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Итого, ₽')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
                ('discount_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка, %')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_hour', models.PositiveSmallIntegerField(default=11, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Час открытия')),
                ('closing_hour', models.PositiveSmallIntegerField(default=23, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Час закрытия')),
                ('min_order_amount', models.PositiveIntegerField(default=700, verbose_name='Минимальная сумма заказа, ₽')),
                ('free_delivery_from', models.PositiveIntegerField(default=700, verbose_name='Бесплатная доставка от, ₽')),
                ('suburban_delivery_fee', models.PositiveIntegerField(default=100, verbose_name='Доставка на окраины, от ₽')),
                ('delivery_time_min', models.PositiveSmallIntegerField(default=45, verbose_name='Мин. время доставки, мин')),
                ('delivery_time_max', models.PositiveSmallIntegerField(default=60, verbose_name='Макс. время доставки, мин')),
            ],
            options={
                'verbose_name': 'Настройки ресторана',
                'verbose_name_plural': 'Настройки ресторана',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена, ₽')),
                ('weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вес, г')),
                ('pieces_amount', models.PositiveSmallIntegerField(help_text='Кусочков в порции или 1 для супа/напитка', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество штук')),
                ('image_url', models.URLField(max_length=500, verbose_name='URL изображения')),
                ('composition', models.JSONField(blank=True, default=list, help_text='Список ингредиентов, например ["Лосось", "Сыр"]', verbose_name='Состав')),
                ('allergens', models.JSONField(blank=True, default=list, help_text='Список аллергенов, например ["Рыба", "Глютен"]', verbose_name='Аллергены')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('benefit_badge', models.CharField(blank=True, help_text='Например: «15% выгода», «Хит»', max_length=50, verbose_name='Бейдж')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для заказа')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['category__sort_order', 'subcategory__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название (снимок)')),
                ('unit_price', models.PositiveIntegerField(verbose_name='Цена за единицу, ₽')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('weight_grams', models.PositiveSmallIntegerField(verbose_name='Вес порции, г')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='api.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.promocode', verbose_name='Промокод'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='baked, warm, classic', max_length=32, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('category', models.ForeignKey(limit_choices_to={'slug': 'rolls'}, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Только для роллов', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.CreateModel(
            name='SetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, help_text='Сколько порций этого продукта входит в сет', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('included_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='included_in_sets', to='api.product', verbose_name='Включённый продукт')),
                ('set_product', models.ForeignKey(limit_choices_to={'category__slug': 'sets'}, on_delete=django.db.models.deletion.CASCADE, related_name='set_items', to='api.product', verbose_name='Сет')),
            ],
            options={
                'verbose_name': 'Позиция в сете',
                'verbose_name_plural': 'Состав сетов',
                'constraints': [models.UniqueConstraint(fields=('set_product', 'included_product'), name='unique_set_item'), models.CheckConstraint(condition=models.Q(('set_product', models.F('included_product')), _negated=True), name='set_cannot_include_itself', violation_error_message='Сет не может включать сам себя.')],
            },
        ),
    ]
