# Generated by Django 6.0.6 on 2026-06-14 10:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Аллерген',
                'verbose_name_plural': 'Аллергены',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='sets, rolls, sushi, hot, desserts, drinks, sauces', max_length=32, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('subtitle', models.CharField(blank=True, help_text='Например: «ЛУЧШИЙ ВЫБОР ДЛЯ КОМПАНИИ»', max_length=200, verbose_name='Подзаголовок секции')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория меню',
                'verbose_name_plural': 'Категории меню',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Код')),
                ('discount_percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка, %')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_hour', models.PositiveSmallIntegerField(default=11, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='Час открытия')),
                ('closing_hour', models.PositiveSmallIntegerField(default=23, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='Час закрытия')),
                ('min_order_amount', models.PositiveIntegerField(default=700, verbose_name='Минимальная сумма заказа, ₽')),
                ('free_delivery_from', models.PositiveIntegerField(default=700, verbose_name='Бесплатная доставка от, ₽')),
                ('suburban_delivery_fee', models.PositiveIntegerField(default=100, verbose_name='Доставка на окраины, от ₽')),
                ('delivery_time_min', models.PositiveSmallIntegerField(default=45, verbose_name='Мин. время доставки, мин')),
                ('delivery_time_max', models.PositiveSmallIntegerField(default=60, verbose_name='Макс. время доставки, мин')),
            ],
            options={
                'verbose_name': 'Настройки ресторана',
                'verbose_name_plural': 'Настройки ресторана',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена, ₽')),
                ('weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вес, г')),
                ('pieces_amount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество штук')),
                ('image', models.ImageField(upload_to='sets/', verbose_name='Изображение')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('benefit_badge', models.CharField(blank=True, help_text='Например: «15% выгода», «Хит»', max_length=50, verbose_name='Бейдж')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для заказа')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Сет',
                'verbose_name_plural': 'Сеты',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('allergens', models.ManyToManyField(blank=True, help_text='Аллергены, которые содержит этот ингредиент (глютен — в муке, моллюски — в мидиях и т.д.)', related_name='ingredients', to='api.allergen', verbose_name='Аллергены')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Новый'), ('confirmed', 'Подтверждён'), ('preparing', 'Готовится'), ('delivering', 'В доставке'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('subtotal', models.PositiveIntegerField(default=0, verbose_name='Сумма без скидки, ₽')),
                ('discount_amount', models.PositiveIntegerField(default=0, verbose_name='Скидка, ₽')),
                ('delivery_fee', models.PositiveIntegerField(default=0, verbose_name='Доставка, ₽')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Итого, ₽')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.promocode', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена, ₽')),
                ('weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вес, г')),
                ('pieces_amount', models.PositiveSmallIntegerField(help_text='Кусочков в порции или 1 для супа/напитка', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество штук')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('benefit_badge', models.CharField(blank=True, help_text='Например: «15% выгода», «Хит»', max_length=50, verbose_name='Бейдж')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для заказа')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['category__sort_order', 'subcategory__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_ingredients', to='api.ingredient', verbose_name='Ингредиент')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ingredients', to='api.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Ингредиент в продукте',
                'verbose_name_plural': 'Ингредиенты в продуктах',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(related_name='products', through='api.ProductIngredient', to='api.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Название (снимок)')),
                ('unit_price', models.PositiveIntegerField(verbose_name='Цена за единицу, ₽')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('weight_grams', models.PositiveSmallIntegerField(verbose_name='Вес порции, г')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='api.product', verbose_name='Продукт')),
                ('set_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='api.set', verbose_name='Сет')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='SetIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='set_ingredients', to='api.ingredient', verbose_name='Ингредиент')),
                ('set_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_ingredients', to='api.set', verbose_name='Сет')),
            ],
            options={
                'verbose_name': 'Ингредиент в сете',
                'verbose_name_plural': 'Ингредиенты в сетах',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='set',
            name='ingredients',
            field=models.ManyToManyField(related_name='sets', through='api.SetIngredient', to='api.ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.CreateModel(
            name='SetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, help_text='Сколько порций этого продукта входит в сет', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('included_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='included_in_sets', to='api.product', verbose_name='Включённый продукт')),
                ('set_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_items', to='api.set', verbose_name='Сет')),
            ],
            options={
                'verbose_name': 'Позиция в сете',
                'verbose_name_plural': 'Состав сетов',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='baked, warm, classic', max_length=32, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('category', models.ForeignKey(limit_choices_to={'slug': 'rolls'}, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Только для роллов', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='api.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AddConstraint(
            model_name='productingredient',
            constraint=models.UniqueConstraint(fields=('product', 'ingredient'), name='unique_product_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('product__isnull', False), ('set_menu__isnull', True)), models.Q(('product__isnull', True), ('set_menu__isnull', False)), _connector='OR'), name='orderitem_product_xor_set', violation_error_message='Должен быть заполнен ровно один: продукт ИЛИ сет.'),
        ),
        migrations.AddConstraint(
            model_name='setingredient',
            constraint=models.UniqueConstraint(fields=('set_menu', 'ingredient'), name='unique_set_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='setitem',
            constraint=models.UniqueConstraint(fields=('set_menu', 'included_product'), name='unique_set_item'),
        ),
    ]
