# Generated by Django 6.0.6 on 2026-06-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], default='delivery', max_length=10, verbose_name='Тип заказа'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='restaurant_address',
            field=models.TextField(blank=True, help_text='Отображается при выборе самовывоза', verbose_name='Адрес ресторана'),
        ),
    ]
