# Generated by Django 6.0.6 on 2026-06-14 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_order_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'Сет', 'verbose_name_plural': 'Сеты'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='code_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Код отправлен'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=4, verbose_name='Код подтверждения'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(help_text='Корневой адрес из DaData: «г Пермь, ул Ленина, д 1»', max_length=500, verbose_name='Адрес (улица, дом)')),
                ('flat', models.CharField(blank=True, max_length=20, verbose_name='Квартира / офис')),
                ('entrance', models.CharField(blank=True, max_length=20, verbose_name='Подъезд')),
                ('floor', models.CharField(blank=True, max_length=20, verbose_name='Этаж')),
                ('intercom', models.CharField(blank=True, max_length=50, verbose_name='Домофон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий курьеру')),
                ('is_default', models.BooleanField(default=False, verbose_name='Основной адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
