# Generated by Django 6.0.6 on 2026-06-14 08:28

from django.db import migrations
from django.utils.text import slugify


def populate_ingredients_and_allergens(apps, schema_editor):
    Product = apps.get_model('api', 'Product')
    Ingredient = apps.get_model('api', 'Ingredient')
    Allergen = apps.get_model('api', 'Allergen')
    ProductIngredient = apps.get_model('api', 'ProductIngredient')

    for product in Product.objects.all():
        # --- Ингредиенты (composition_old) ---
        if product.composition_old:
            for idx, name in enumerate(product.composition_old):
                name = name.strip()
                if not name:
                    continue
                # Убираем слишком длинные имена (slug max 64)
                base_slug = slugify(name, allow_unicode=True)[:60]
                slug = base_slug
                counter = 1
                while Ingredient.objects.filter(slug=slug).exists():
                    slug = f'{base_slug}-{counter}'[:64]
                    counter += 1
                ingredient, _ = Ingredient.objects.get_or_create(
                    name=name,
                    defaults={'slug': slug},
                )
                ProductIngredient.objects.get_or_create(
                    product=product,
                    ingredient=ingredient,
                    defaults={'sort_order': idx},
                )

        # --- Аллергены (allergens_old) ---
        if product.allergens_old:
            for name in product.allergens_old:
                name = name.strip()
                if not name:
                    continue
                base_slug = slugify(name, allow_unicode=True)[:60]
                slug = base_slug
                counter = 1
                while Allergen.objects.filter(slug=slug).exists():
                    slug = f'{base_slug}-{counter}'[:64]
                    counter += 1
                allergen, _ = Allergen.objects.get_or_create(
                    name=name,
                    defaults={'slug': slug},
                )
                product.allergens.add(allergen)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_ingredient_allergen'),
    ]

    operations = [
        migrations.RunPython(
            populate_ingredients_and_allergens,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
