# Generated by Django 6.0.6 on 2026-06-14 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_options_alter_set_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='pickup_discount_percent',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка за самовывоз, %'),
        ),
    ]
