# Generated by Django 6.0.6 on 2026-06-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_pickup_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card_delivery', 'Картой при получении'), ('card_online', 'Картой онлайн')], default='card_online', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Не оплачен'), ('pending', 'Новый'), ('confirmed', 'Подтверждён'), ('preparing', 'Готовится'), ('ready', 'Можно забирать'), ('delivering', 'В доставке'), ('delivered', 'Доставлен'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
