# Generated by Django 6.0.6 on 2026-06-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_populate_ingredients_allergens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allergens_old',
        ),
        migrations.RemoveField(
            model_name='product',
            name='composition_old',
        ),
    ]
