# Generated by Django 6.0.6 on 2026-06-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='ID платежа в ЮKassa'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='order',
            name='yookassa_status',
            field=models.CharField(blank=True, max_length=20, verbose_name='Статус платежа в ЮKassa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Не оплачен'), ('awaiting_payment', 'Ожидает оплаты'), ('pending', 'Новый'), ('confirmed', 'Подтверждён'), ('preparing', 'Готовится'), ('ready', 'Можно забирать'), ('delivering', 'В доставке'), ('delivered', 'Доставлен'), ('completed', 'Выполнен'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
