# Generated by Django 6.0.6 on 2026-06-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_yookassa_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='delivery_zone',
            field=models.CharField(blank=True, choices=[('free_delivery', 'Бесплатная'), ('800_delivery', '800 зона')], help_text='Кэшируется при сохранении адреса по координатам', max_length=20, null=True, verbose_name='Зона доставки'),
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Из DaData geo_lat', max_digits=9, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Из DaData geo_lon', max_digits=9, null=True, verbose_name='Долгота'),
        ),
    ]
