# Generated by Django 6.0.6 on 2026-06-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_address_coordinates_and_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Телефон'),
        ),
    ]
