# Generated by Django 6.0.6 on 2026-06-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dismissed',
            field=models.BooleanField(default=False, help_text='Пользователь подтвердил отмену/завершение — заказ не показывается в активных', verbose_name='Скрыт пользователем'),
        ),
    ]
