# Generated by Django 6.0.6 on 2026-06-27 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_order_dismissed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, help_text='Заполняется кассиром/менеджером при отмене заказа', verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('cashier', 'Кассир'), ('chef', 'Шеф-повар'), ('manager', 'Управляющий')], default='cashier', max_length=10, verbose_name='Роль в дашборде'),
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('cashier', 'Кассир'), ('chef', 'Шеф-повар'), ('manager', 'Управляющий'), ('system', 'Система')], default='system', max_length=10, verbose_name='Роль')),
                ('action', models.TextField(verbose_name='Действие')),
                ('type', models.CharField(choices=[('order', 'Заказ'), ('menu', 'Меню'), ('system', 'Система')], default='system', max_length=10, verbose_name='Тип')),
                ('target_id', models.CharField(blank=True, help_text='ID заказа или позиции меню, к которой относится действие', max_length=64, verbose_name='ID цели')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог операции',
                'verbose_name_plural': 'Логи операций',
                'ordering': ['-created_at'],
            },
        ),
    ]
