# Generated by Django 6.0.6 on 2026-06-27 22:03
# Data migration: гарантированно создаёт staff-пользователей для дашборда.

from django.contrib.auth.hashers import make_password
from django.db import migrations


def seed_staff_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('api', 'UserProfile')

    staff_users = [
        {
            'username': '+79120000001',
            'password': 'admin123',
            'is_staff': True,
            'phone': '+79120000001',
            'role': 'manager',
        },
        {
            'username': '+79120000002',
            'password': 'cashier123',
            'is_staff': True,
            'phone': '+79120000002',
            'role': 'cashier',
        },
        {
            'username': 'admin',
            'password': 'admin123',
            'is_staff': True,
            'is_superuser': True,
            'phone': 'admin',
            'role': 'manager',
        },
    ]

    for data in staff_users:
        phone = data.pop('phone')
        role = data.pop('role')
        password = data.pop('password')
        data['password'] = make_password(password)
        user, created = User.objects.update_or_create(
            username=data['username'],
            defaults=data,
        )
        UserProfile.objects.update_or_create(
            user=user,
            defaults={'phone': phone, 'role': role},
        )


def reverse_func(apps, schema_editor):
    """Откат — ничего не делаем, просто пасс."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_order_cancel_reason_userprofile_role_operationlog'),
    ]

    operations = [
        migrations.RunPython(seed_staff_users, reverse_func),
    ]
