[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py
testpaths = api
addopts = --tb=short --strict-markers -p no:cacheprovider
filterwarnings =
    ignore::DeprecationWarning:factory.*
    ignore::RuntimeWarning:django.db.models.fields
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    smoke: smoke tests (critical path)
